name: Go test coverage check

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Install dependencies
        run: go mod download
      - name: Install go-test-coverage
        run: go install github.com/vladopajic/go-test-coverage/v2@latest
      - name: Start cluster
        uses: medyagh/setup-minikube@master
        # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Test coverage
        run: go test -coverprofile=coverage.out ./...
      - name: Coverage report 
        run: 	~/go/bin/go-test-coverage --profile=cover.out --local-prefix="github.com/headlamp-k8s/headlamp/backend"