name: Go test coverage check

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Start cluster
        uses: medyagh/setup-minikube@master
        # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: generate test coverage
        run: cd backend && ls && go test ./... -coverprofile=./cover.out
      - name: cat cover.out
        run: cat ./backend/cover.out
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        env:
          RUNNER_WORKSPACE: ${{ github.workspace }}/backend
        with:
          # Configure action using config file (option 1)
          # config: ./.testcoverage.yml
          # Configure action by specifying input parameters individually (option 2)
          profile: ./backend/cover.out
          local-prefix: github.com/headlamp-k8s/headlamp/backend
          threshold-file: 80
          threshold-package: 80
          threshold-total: 95
